import turtle
zizi=turtle.Turtle()
zizi.speed(0)
zizi.pensize(10)
zizi.penup()
zizi.forward(10)
zizi.right(90)
zizi.forward(10)
zizi.pencolor('green')
zizi.pendown()
zizi.circle(100)
zizi.left(90)
zizi.penup()
zizi.forward(320)
zizi.left(90)
zizi.forward(100)
zizi.pencolor('red')
zizi.pendown()
zizi.circle(100)
zizi.penup()
zizi.left(90)
zizi.penup()
zizi.forward(240)
zizi.right(90)
zizi.pencolor('black')
zizi.pendown()
zizi.circle(100)
zizi.penup()
zizi.left(90)
zizi.forward(240)
zizi.right(90)
zizi.pencolor('blue')
zizi.pendown()
zizi.circle(100)
zizi.penup()
zizi.backward(10)
zizi.right(270)
zizi.backward(25)
zizi.pendown()
zizi.pencolor('yellow')
zizi.circle(100)




input()